spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eyecool
    username: eyecool
    password: eyecool
    driver-class-name: org.mariadb.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10